# Generated by Django 5.0.10 on 2026-01-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(unique=True)),
                ('tasa_base', models.DecimalField(decimal_places=4, max_digits=7)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['numero_cuota'],
            },
        ),
        migrations.CreateModel(
            name='ParametroFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva', models.DecimalField(decimal_places=2, default=21.0, max_digits=5)),
                ('iva_financiacion', models.DecimalField(decimal_places=2, default=10.5, max_digits=5)),
                ('comision_pago_tech', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('arancel_plataforma', models.DecimalField(decimal_places=2, default=1.8, max_digits=5)),
            ],
            options={
                'verbose_name': 'Parámetros Financieros',
            },
        ),
    ]
