# Generated by Django 5.0.10 on 2026-01-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_cuotaconfig_parametrofinanciero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaconfig',
            name='nombre',
            field=models.CharField(default='Cuotas', max_length=100),
        ),
        migrations.AlterField(
            model_name='cuotaconfig',
            name='numero_cuota',
            field=models.IntegerField(),
        ),
    ]
