# Generated by Django 5.0.10 on 2026-01-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_cuotaconfig_nombre_alter_cuotaconfig_numero_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrofinanciero',
            name='arancel_plataforma_debito',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=5),
        ),
        migrations.AddField(
            model_name='parametrofinanciero',
            name='comision_pago_tech_debito',
            field=models.DecimalField(decimal_places=2, default=3.49, max_digits=5),
        ),
    ]
