# Generated by Django 5.2.4 on 2026-03-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_parametrofinanciero_arancel_plataforma_debito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaconfig',
            name='arancel_aplica_iva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuotaconfig',
            name='arancel_credito_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cuotaconfig',
            name='arancel_debito_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cuotaconfig',
            name='com_credito_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cuotaconfig',
            name='com_debito_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cuotaconfig',
            name='comision_aplica_iva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuotaconfig',
            name='iva_financiacion_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cuotaconfig',
            name='iva_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
