# Generated by Django 5.2.4 on 2026-03-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_cuotaconfig_arancel_aplica_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaconfig',
            name='tasa_aplica_iva_fin',
            field=models.BooleanField(default=True),
        ),
    ]
