# Generated by Django 5.2.4 on 2026-04-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_linkpago_desglose_arancel_linkpago_desglose_comision_and_more'),
        ('app2', '0006_cuotaconfig_tasa_aplica_iva_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaconfig',
            name='alcance',
            field=models.CharField(choices=[('global', 'Global — visible para todos'), ('usuarios', 'Personalizado — solo usuarios asignados')], default='global', max_length=20),
        ),
        migrations.AddField(
            model_name='cuotaconfig',
            name='usuarios_asignados',
            field=models.ManyToManyField(blank=True, related_name='planes_personalizados', to='app1.cliente'),
        ),
    ]
