# Generated by Django 5.2.4 on 2026-05-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_cuotaconfig_alcance_cuotaconfig_usuarios_asignados'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Identificador interno ej: naranja_x', unique=True)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('arancel', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('iva', models.DecimalField(decimal_places=2, default=21, max_digits=5)),
                ('aplica_iva', models.BooleanField(default=True)),
                ('acepta_cuotas', models.BooleanField(default=False, help_text='Si permite financiacion en cuotas')),
                ('activa', models.BooleanField(default=True)),
                ('icono', models.CharField(blank=True, default='fas fa-credit-card', help_text='Clase Font Awesome ej: fas fa-credit-card', max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden en el formulario')),
            ],
            options={
                'verbose_name': 'Tarjeta Custom',
                'verbose_name_plural': 'Tarjetas Custom',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
