# Generated by Django 5.2.4 on 2026-05-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_tarjetacustom'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetacustom',
            name='payzen_code',
            field=models.CharField(blank=True, default='', help_text='Codigo Payzen ej: NARANJA, CABAL, CABAL_DEBIT, TUYA', max_length=50),
        ),
    ]
