# Generated by Django 5.2.4 on 2026-05-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_tarjetacustom_payzen_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_admin',
            name='ultima_actividad_mensajes',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
