# Generated by Django 5.2.4 on 2026-05-15 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_user_admin_ultima_actividad_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaconfig',
            name='tarjeta_custom',
            field=models.ForeignKey(blank=True, help_text='Si se asigna, este plan solo aparece para esta tarjeta. Vacío = crédito genérico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_cuotas', to='app2.tarjetacustom'),
        ),
    ]
