# Generated by Django 5.2.4 on 2026-05-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_cuotaconfig_tarjeta_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminosCondiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, unique=True)),
                ('contenido', models.TextField(help_text='Formato Markdown')),
                ('activa', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('updated_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Términos y Condiciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
