# Generated by Django 5.2.4 on 2025-12-12 13:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cliente_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuotas', models.PositiveSmallIntegerField(default=1)),
                ('tipo_tarjeta', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], default='credito', max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('receiver_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('link', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_text', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app1.cliente')),
            ],
        ),
    ]
