# Generated by Django 5.2.4 on 2025-12-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_linkpago'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpago',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='linkpago',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
