# Generated by Django 5.2.4 on 2025-12-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_linkpago_order_id_linkpago_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpago',
            name='cuotas_elegidas',
            field=models.IntegerField(default=1),
        ),
    ]
