# Generated by Django 5.0.10 on 2026-01-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_linkpago_cuotas_elegidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpago',
            name='auth_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='linkpago',
            name='lote_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='linkpago',
            name='nro_transaccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
