# Generated by Django 5.0.10 on 2026-02-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_linkpago_auth_code_linkpago_lote_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpago',
            name='status_detalle',
            field=models.CharField(default='INITIAL', help_text='Estado detallado desde PayZen', max_length=50),
        ),
    ]
