# Generated by Django 5.0.10 on 2026-03-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_linkpago_status_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpago',
            name='lote_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
