# Generated by Django 5.2.4 on 2026-03-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_linkpago_lote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpago',
            name='desglose_arancel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='linkpago',
            name='desglose_comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='linkpago',
            name='desglose_cuota_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='linkpago',
            name='desglose_iva_105',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='linkpago',
            name='desglose_iva_21',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='linkpago',
            name='desglose_tasa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
