# Generated by Django 5.2.4 on 2026-04-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_linkpago_desglose_arancel_linkpago_desglose_comision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
