# Generated by Django 5.2.4 on 2026-05-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_cliente_acepto_tyc_cliente_fecha_acepto_tyc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='recibir_liquidacion_email',
            field=models.BooleanField(default=True),
        ),
    ]
