# Generated by Django 5.2.4 on 2026-05-02 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_cliente_recibir_liquidacion_email'),
        ('app2', '0007_cuotaconfig_alcance_cuotaconfig_usuarios_asignados'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('es_admin', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='app2.user_admin')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='app1.cliente')),
                ('link_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='app1.linkpago')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
