# Generated by Django 5.2.4 on 2026-05-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_mensajeinterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeinterno',
            name='conversacion_cerrada',
            field=models.BooleanField(default=False),
        ),
    ]
