# Generated by Django 5.2.4 on 2026-05-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_mensajeinterno_conversacion_cerrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ultima_actividad_mensajes',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
