# Generated by Django 5.2.4 on 2026-05-03 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_cliente_ultima_actividad_mensajes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cerrada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_chat', to='app1.cliente')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='mensajeinterno',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='app1.sesionchat'),
        ),
    ]
