# Generated by Django 5.2.4 on 2026-05-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_sesionchat_mensajeinterno_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
