# Generated by Django 5.2.4 on 2026-05-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_cliente_fecha_aprobacion_cliente_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
