# Generated by Django 6.1.1 on 2026-09-08 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_cliente_fecha_registro'),
        ('app2', '0012_terminoscondiciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpago',
            name='tipo_tarjeta',
            field=models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], default='credito', max_length=50),
        ),
        migrations.CreateModel(
            name='RechazoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('comentario', models.TextField(help_text='Motivo del rechazo')),
                ('rechazado_en', models.DateTimeField(auto_now_add=True)),
                ('rechazado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechazos', to='app2.user_admin')),
            ],
            options={
                'verbose_name': 'Rechazo de Solicitud',
                'verbose_name_plural': 'Rechazos de Solicitudes',
                'ordering': ['-rechazado_en'],
            },
        ),
    ]
