# Generated by Django 6.1.1 on 2026-09-08 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_rechazosolicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='principal',
            field=models.ForeignKey(blank=True, help_text='Usuario principal al que pertenece este operador', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='app1.cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.CharField(choices=[('principal', 'Principal'), ('secundario', 'Secundario / Operador')], default='principal', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='username',
            field=models.CharField(blank=True, help_text='Nombre de usuario único para iniciar sesión', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='linkpago',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Operador que generó este link (puede ser el principal u otro operador)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_creados', to='app1.cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
